// src/pages/Home/Index.vue
<script setup lang="ts">
import { nextTick, onBeforeMount, onMounted, ref } from "@vue/runtime-core";
import axios from "axios";
import { useRouter } from "vue-router";
import auth from "../../shared/auth";

interface IContact {
  id: number;
  name: string;
  email: string;
  message: string;
}

const apiUrl = "https://contact-me-api.vercel.app";
const router = useRouter();
const contacts = ref<IContact[]>([]);
const renderList = ref(true);

function handleSignOut() {
  auth.SignOut();
}

async function handleDelete(id: number, index: number) {
  try {
    const res = await axios.get(
      `${apiUrl}/contacts/delete/${auth.UserData()?.id}/${id}`
    );

    contacts.value.splice(index, 1);

    reRenderList();

    alert(res.data.message);
  } catch (err) {
    alert("An unexpected error occurred, try again!");
  }
}

function reRenderList() {
  renderList.value = false;
  nextTick(() => {
    renderList.value = true;
  });
}

onMounted(async () => {
  const res = await axios.get(
    `${apiUrl}/contacts/get/all/${auth.UserData()?.id}`
  );

  contacts.value = res.data.contacts;
});

onBeforeMount(() => {
  if (!auth.UserData()?.id) {
    router.push("/login");
  }
});
</script>

<template>
  <div>
    <button @click="handleSignOut">Sign Out</button>

    <div class="contacts" v-if="renderList">
      <div
        class="contact"
        v-for="(contact, index) in contacts"
        :key="contact.id"
      >
        <h3>{{ contact.name }} - {{ contact.id }}</h3>
        <p>
          <strong>{{ contact.email }}</strong>
        </p>

        <p>{{ contact.message }}</p>

        <button @click="handleDelete(contact.id, index)">Delete Contact</button>
      </div>
    </div>
  </div>
</template>

<style lang="scss" scoped></style>

// src/pages/home/index.tsx
import React, { useEffect, useState } from 'react'
import { useHistory } from 'react-router-dom'
import axios from 'axios'
import './home.scss'

type Contacts = {
  name: string;
  email: string;
  message: string;
  createdAt: Date;
  _id: string;
  __v: number;
  UID?: string;
}[]

export function Home() {
  const [contacts, setContacts] = useState<Contacts>([])
  const [token, setToken] = useState(localStorage.getItem('token') || '')
  const history = useHistory()

  useEffect(() => {
    if(!token) {
      history.push('/login')
      return
    }

    async function checkToken() {
      try {
        const res = await axios.post('https://my-contact-api.herokuapp.com/validate-token', {token})
  
        localStorage.setItem('token', res.data.token._id)
        setToken(res.data.token._id)
      }catch(err) {
        alert(err.message)
        localStorage.setItem('token', '')
        history.push('/login')
      }
    }
    checkToken()

    async function getContacts() {
      try {
        const res = await axios.post('https://my-contact-api.herokuapp.com/get-contacts', {token})
        setContacts(res.data)
      }catch(err) {
        alert(err.message)
      }
    }
    getContacts()
  }, [contacts, token])

  async function deleteContact(index: number, id: string) {

    try {
      await axios.post('https://my-contact-api.herokuapp.com/delete-contact', {
        id,
        token,
      })

      setContacts(contacts.splice(index, 1))
    }catch(err) {
      console.log(err);
    }

  }

  return (
    <div id="home">
      <h2>Home page</h2>
      
      <div>
        {
          contacts.map((item, key) => (
            <div key={key}>
              <h3>{item.name}</h3>
              <small>{new Date(item.createdAt).toLocaleString()}, {item.email}</small>
              <p>{item.message}</p>
              <button onClick={() => deleteContact(key, item._id)}>Delete</button>
            </div>
          ))
        }
      </div>
    </div>
  )
}
